### ISSUE TITLE
Support for raspberry pi?

### ISSUE THREAD

**Issue by AnderssonPeter** [Mickaelh51/ser2net-docker#1]
Hi any chance you could make the image multi arch and add support for ARM64?

**Comment by AnderssonPeter** [comment]
I have created a github actions pipeline that does the job https://github.com/AnderssonPeter/ser2net-docker/blob/main/.github/workflows/publish.yml
It currently pushes to github packages instead of docker hub, but feel free to copy it and modify it to push to docker hub instead.

**Comment by Mickaelh51** [comment]
Hi,
sorry for the delay
you can find a image built for rpi:
``https://hub.docker.com/layers/mickaelh51/ser2net/4.3.3-rpi/images/sha256-4807bbcab60b9c03a65c11804c1d7131881a81410615cceb17f7272a80813692?context=explore`

can you test it please ?

thanks in advance

**Comment by AnderssonPeter** [comment]
Hi I made my own image by now. But thanks for the response.
